image: node:18.16.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install 
  - test -e package.json && npm install
  - hexo generate

pages:
  script:
    - npm run build
  artifacts:
    paths:
      - dist
